// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8YiPBt1JNNOSe_oar5KEC_GDEYUoP0I8',
    appId: '1:791307818531:web:019171afc9c08e07ef8396',
    messagingSenderId: '791307818531',
    projectId: 'calendar-27f58',
    authDomain: 'calendar-27f58.firebaseapp.com',
    storageBucket: 'calendar-27f58.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB96UTOP-a61a5J79Lmpn8rplF_7BotWCQ',
    appId: '1:791307818531:android:221d0ef770b5c52fef8396',
    messagingSenderId: '791307818531',
    projectId: 'calendar-27f58',
    storageBucket: 'calendar-27f58.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTk5osuXhyf-zqM6qh-Zuq3RHtREWNMqw',
    appId: '1:791307818531:ios:7e43fe22de229ffaef8396',
    messagingSenderId: '791307818531',
    projectId: 'calendar-27f58',
    storageBucket: 'calendar-27f58.firebasestorage.app',
    iosBundleId: 'com.example.sharedCalendar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBTk5osuXhyf-zqM6qh-Zuq3RHtREWNMqw',
    appId: '1:791307818531:ios:7e43fe22de229ffaef8396',
    messagingSenderId: '791307818531',
    projectId: 'calendar-27f58',
    storageBucket: 'calendar-27f58.firebasestorage.app',
    iosBundleId: 'com.example.sharedCalendar',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD8YiPBt1JNNOSe_oar5KEC_GDEYUoP0I8',
    appId: '1:791307818531:web:280d53595ca35a3def8396',
    messagingSenderId: '791307818531',
    projectId: 'calendar-27f58',
    authDomain: 'calendar-27f58.firebaseapp.com',
    storageBucket: 'calendar-27f58.firebasestorage.app',
  );
}
